const icon = {
  directory: 'bi bi-folder2',
  file: 'bi bi-file-earmark-text',
  link: 'bi bi-link',
  linkOut: 'bi bi-box-arrow-up-left',
  modeDark: 'bi bi-moon-stars-fill',
  modeLight: 'bi bi-sun-fill',
  home: 'bi bi-house-fill',
  account: 'bi bi-person-fill',
  list: 'bi bi-list',
  listNested: 'bi bi-list-nested',
  listBullet: 'bi bi-list-ul',
  grid: 'bi bi-grid',
  gridSmall: 'bi bi-grid-3x3-gap',
  book: 'bi bi-book',
  arrowStart: 'bi bi-arrow-left',
  arrowEnd: 'bi bi-arrow-right',
  chevronStart: 'bi bi-chevron-left',
  chevronEnd: 'bi bi-chevron-right',
  table: 'bi bi-table',
  caretUp: 'bi bi-caret-up-fill',
  caretDown: 'bi bi-caret-down-fill',
  boxCheck: 'bi bi-check2-square',
  boxUncheck: 'bi bi-square',
  crudDelete: 'bi bi-trash',
  crudDetail: 'bi bi-view-list',
  crudEdit: 'bi bi-pen',
  crudAdd: 'bi bi-plus-circle',
  slider: 'bi bi-sliders',
  gear: 'bi bi-gear',
  stat: 'bi bi-graph-up'
}

export default icon
